log:
  path: /Users/Fendam/logs
  level: debug

system:
  token:
    aesKey: B273A23452AACDEF
    tokenDuration: P2D
  redis:
    cacheEntryTtl: PT1M
  jwt:
    secretKey: 123D2231xasd1a
    duration: PT1000S
spring:
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      #mysql
      #      driverClassName: com.p6spy.engine.spy.P6SpyDriver
      #      url: jdbc:p6spy:mysql://mysql.jyoou.com/dev_test?useUnicode=true&characterEncoding=UTF-8
      #oracle
      driverClassName: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@81.68.224.107:6581:orcl
      username: jn_salary
      password: jn_salary#dev20211028
      # 初始化连接大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      max-active: 20
      max-wait: 30000
      # 可关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      keep-alive: true
      validation-query-timeout: 2000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
      web-stat-filter:
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"

  redis:
    database: 1
    host: 129.211.43.143
    password: '8qLRzBjvgq20'
    port: 6379
    timeout: PT30S
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        min-idle: 2 # 连接池中的最小空闲连接
        max-wait: PT30S # 连接池最大阻塞等待时间（使用负值表示没有限制）
feign:
  client:
    config:
      default:
        connectTimeout: 5000  #配置所有服务连接超时
        readTimeout: 15000	#配置所有服务等待超时

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.hntec.salary.db.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

xxl:
  job:
    accessToken: ''
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    executor:
      appname: ${spring.application.name}
      ip:
      port: 9996
      logretentiondays: -1

minio:
  endpoint: http://localhost:9000
  bucket-name: test
  access-key: admin
  secret-key: password
